name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - name: Setup Node
      uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
