name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Setup Node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
